spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/francis-chen/config-repo.git
          username: 15527804816@163.com
          password: cisyunhua98
          basedir: E:\localhost\config
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
# 将项目部署到rancher上 设置服务之间可以访问
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
